const XLSX = globalThis.XLSX
import { parseTimetable, parseSubstitutionLog, calculateCandidates } from './logic.js'

const state = { timetable: null, workbook: null, log: null, sheet: '', adjustments: {}, records: [], last: null }
const weekdays = ['일','월','화','수','목','금','토']; const today = new Date().toISOString().slice(0,10)
document.querySelector('#app').innerHTML = `
<header><div class="brand">결보강 추천</div><div class="privacy"><strong>🔒 개인정보 보호</strong><span>선택한 Excel 파일과 교사 정보는 이 브라우저 안에서만 처리되며 서버로 업로드되지 않습니다. 새로고침하거나 창을 닫으면 불러온 정보와 작업 기록이 사라집니다.</span></div></header>
<main><section class="hero"><p class="eyebrow">SCHOOL SCHEDULE ASSISTANT</p><h1>결강 시간만 선택하면,<br><em>가장 적합한 보강 교사</em>를 찾아드려요.</h1><p>두 Excel 파일을 불러온 뒤 날짜와 교시를 선택하세요. 모든 계산은 현재 브라우저에서만 진행됩니다.</p></section>
<section class="panel files"><h2><b>1</b> Excel 파일 불러오기</h2><div class="file-grid"><label class="drop"><span class="icon">▦</span><strong>교사 주간시간표</strong><small>.xlsx 또는 .xls 파일</small><input id="timetable" type="file" accept=".xlsx,.xls"><span class="choose">파일 선택</span><span id="timeStatus" class="status"></span></label><label class="drop"><span class="icon">▤</span><strong>결보강 일지</strong><small>.xlsx 또는 .xls 파일</small><input id="log" type="file" accept=".xlsx,.xls"><span class="choose">파일 선택</span><span id="logStatus" class="status"></span></label></div><div id="validation" class="validation hidden"></div><div id="error" class="error hidden"></div></section>
<section class="panel search"><h2><b>2</b> 결강 시간 선택</h2><div class="controls"><label>날짜 선택<input id="date" type="date" value="${today}"></label><label>교시 선택<select id="period"><option value="">파일을 먼저 불러오세요</option></select></label><label>기준 시트<select id="sheet" disabled><option>일지를 먼저 불러오세요</option></select></label><button id="find" class="primary" disabled>보강 교사 찾기 →</button></div></section>
<section id="results" class="hidden"></section>
<section class="panel records"><div class="section-head"><div><p class="eyebrow">SESSION LOG</p><h2>오늘 배정 기록</h2></div><button id="reset" class="ghost">이번 작업 기록 초기화</button></div><div id="recordList" class="empty">아직 배정한 기록이 없습니다.</div></section>
</main><footer>이 앱은 파일을 업로드하거나 저장하지 않습니다. 데이터는 탭을 닫으면 사라집니다.</footer>`

const $ = id => document.getElementById(id); const error = msg => { $('error').textContent = msg; $('error').classList.toggle('hidden', !msg) }
async function read(file) { return XLSX.read(await file.arrayBuffer(), { type:'array' }) }
const sheetRows = (wb, name) => XLSX.utils.sheet_to_json(wb.Sheets[name], { header:1, defval:'', raw:true })

$('timetable').onchange = async e => { try { error(''); const wb=await read(e.target.files[0]); const name=wb.SheetNames.includes('주간시간표')?'주간시간표':wb.SheetNames[0]; state.timetable=parseTimetable(sheetRows(wb,name)); $('timeStatus').textContent='✓ 시간표 불러오기 완료'; update() } catch(ex){ state.timetable=null; error(ex.message); update() } }
$('log').onchange = async e => { try { error(''); state.workbook=await read(e.target.files[0]); const sel=$('sheet'); sel.innerHTML=state.workbook.SheetNames.map(n=>`<option>${escapeHtml(n)}</option>`).join(''); sel.disabled=false; selectMonth(); loadLog(); $('logStatus').textContent='✓ 결보강 일지 불러오기 완료'; update() } catch(ex){ state.log=null; error(ex.message); update() } }
$('date').onchange = () => { selectMonth(); if(state.workbook) loadLog(); updatePeriods() }
$('sheet').onchange = () => { loadLog(); update() }
function selectMonth(){ if(!state.workbook)return; const m=Number($('date').value.slice(5,7)); const preferred=m===1?'12월1월':`${m}월`; if(state.workbook.SheetNames.includes(preferred)) $('sheet').value=preferred }
function loadLog(){ try { state.sheet=$('sheet').value; state.log=parseSubstitutionLog(sheetRows(state.workbook,state.sheet)); error('') } catch(ex){state.log=null;error(ex.message)} }
function updatePeriods(){ const date=new Date(`${$('date').value}T00:00:00`); const day=weekdays[date.getDay()]; const periods=state.timetable?.periodsByDay[day]||[]; $('period').innerHTML=periods.length?periods.map(p=>`<option value="${p}">${p}교시</option>`).join(''):'<option value="">선택한 요일에 교시가 없습니다</option>'; $('find').disabled=!(state.timetable&&state.log&&periods.length) }
function update(){ updatePeriods(); if(state.timetable&&state.log){ const names=new Set(state.log.map(x=>x.name.trim())); const absent=state.timetable.teachers.filter(x=>!names.has(x.name)).length; const eighteen=state.timetable.teachers.filter(x=>x.hours==='18').length; $('validation').innerHTML=`<span>시간표 교사 <b>${state.timetable.teachers.length}명</b></span><span>결보강 순번 교사 <b>${state.log.length}명</b></span><span>18시수 제외 <b>${eighteen}명</b></span><span>순번표에 없음 <b>${absent}명</b></span>`; $('validation').classList.remove('hidden'); if(!state.timetable.teachers.some(x=>names.has(x.name))) error('시간표와 결보강 일지의 교사명을 매칭할 수 없습니다.') } }
function escapeHtml(v){ const d=document.createElement('div');d.textContent=String(v);return d.innerHTML }
function run(){ const date=new Date(`${$('date').value}T00:00:00`), day=weekdays[date.getDay()], period=Number($('period').value); state.last={date:$('date').value,day,period}; const result=calculateCandidates(state.timetable.teachers,state.log,day,period,state.adjustments); renderResults(result) }
$('find').onclick=run
function details(c){return `<div class="metrics"><span><small>현재 보강 누계</small><b>${c.total}회</b></span><span><small>오늘 기존 수업</small><b>${c.existing.length?c.existing.map(p=>p+'교시').join(' · '):'없음'}</b></span><span><small>보강 후</small><b>총 ${c.after}시간</b></span></div>`}
function renderResults({candidates,excluded}){ const top=candidates.slice(0,5); $('results').innerHTML=`<section class="recommend"><p class="eyebrow">RECOMMENDATION</p>${top.length?`<div class="winner"><span class="rank-label">다음 보강 1순위</span><div class="winner-row"><div><h2>${escapeHtml(top[0].name)} <small>선생님</small></h2>${details(top[0])}</div><button class="assign" data-name="${escapeHtml(top[0].name)}">배정</button></div></div><div class="others">${top.slice(1).map((c,i)=>`<article><span class="rank">${i+2}</span><div class="person"><h3>${escapeHtml(c.name)} <small>선생님</small></h3>${details(c)}</div><button class="assign" data-name="${escapeHtml(c.name)}">배정</button></article>`).join('')}</div>`:'<div class="no-result">조건을 만족하는 추천 교사가 없습니다.</div>'}<details class="excluded"><summary>제외된 교사 보기 <span>${excluded.length}명</span></summary><div>${excluded.map(x=>`<p><b>${escapeHtml(x.name)}</b><span>${x.reasons.map(escapeHtml).join(' · ')}</span></p>`).join('')||'<p>제외된 교사가 없습니다.</p>'}</div></details></section>`; $('results').classList.remove('hidden'); document.querySelectorAll('.assign').forEach(b=>b.onclick=()=>assign(b.dataset.name)); $('results').scrollIntoView({behavior:'smooth'}) }
function assign(name){ const entry=state.log.find(x=>x.name.trim()===name), before=entry.total+(state.adjustments[name]||0); state.adjustments[name]=(state.adjustments[name]||0)+1; state.records.push({id:crypto.randomUUID(),...state.last,name,before,after:before+1,time:new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}); renderRecords(); run() }
function renderRecords(){ $('recordList').className=state.records.length?'record-list':'empty'; $('recordList').innerHTML=state.records.length?state.records.map(r=>`<div><span class="record-date">${r.date} (${r.day}) · ${r.period}교시</span><b>${escapeHtml(r.name)} 선생님</b><span>${r.before}회 → ${r.after}회 · ${r.time}</span><button data-id="${r.id}">배정 취소</button></div>`).join(''):'아직 배정한 기록이 없습니다.'; $('recordList').querySelectorAll('button').forEach(b=>b.onclick=()=>cancel(b.dataset.id)) }
function cancel(id){ const i=state.records.findIndex(r=>r.id===id);if(i<0)return; state.adjustments[state.records[i].name]--;state.records.splice(i,1);renderRecords();if(state.last)run() }
$('reset').onclick=()=>{state.adjustments={};state.records=[];renderRecords();if(state.last)run()}
